name: Build deb package

on:
  push:
    tags: 'v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts equivs \
            build-essential fakeroot

      - name: Build
        run: 
          ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.tar.xz
            build/*.dsc
          tag_name: "${{github.ref_name}}"
